//! Deterministic seedable RNG — `xoshiro128**` (Blackman & Vigna). 16 bytes of
//! state, fast, public reference vectors, fits inside `Sim`. Runtime default
//! Rust implementation; a hand-authored WAT implementation lands in plan 3 and
//! is differentially tested against this one.

/// Seedable xoshiro128** RNG. The internal state is 16 bytes (four `u32`).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Rng {
    s: [u32; 4],
}

impl Rng {
    /// Seed the RNG from a single `u64`. State is expanded with `SplitMix64`,
    /// per the reference seeding strategy from the xoshiro authors. All-zero
    /// state is forbidden by xoshiro and `Rng::seed(0)` therefore advances the
    /// `SplitMix64` stream once before populating the first lane.
    #[must_use]
    pub fn seed(seed: u64) -> Self {
        let mut mixer = SplitMix64::new(seed);
        let s = [
            mixer.next_u32(),
            mixer.next_u32(),
            mixer.next_u32(),
            mixer.next_u32(),
        ];
        debug_assert!(
            s.iter().any(|&w| w != 0),
            "xoshiro128** rejects all-zero state"
        );
        Self { s }
    }

    /// Draw the next `u32` and advance state.
    pub fn next_u32(&mut self) -> u32 {
        let result = self.s[1].wrapping_mul(5).rotate_left(7).wrapping_mul(9);
        let t = self.s[1] << 9;

        self.s[2] ^= self.s[0];
        self.s[3] ^= self.s[1];
        self.s[1] ^= self.s[2];
        self.s[0] ^= self.s[3];
        self.s[2] ^= t;
        self.s[3] = self.s[3].rotate_left(11);

        result
    }

    /// Snapshot the internal state as four little-endian-ordered `u32`
    /// words. Used by `Sim::state_hash` to canonicalise RNG advance into
    /// the state digest, by `hub-hardlang`'s differential test to seed
    /// both backends from a shared `SplitMix64` expansion, and acceptable
    /// for production callers that need to persist RNG state (e.g. into
    /// a save-file header). Dual of [`Rng::from_state`].
    #[must_use]
    pub fn state(&self) -> [u32; 4] {
        self.s
    }

    /// Construct an `Rng` directly from raw `[u32; 4]` state. Used by
    /// `hub-hardlang`'s differential test to seed the WAT and Rust
    /// backends from a shared `SplitMix64` expansion, and acceptable for
    /// production callers that have their own seed-expansion strategy
    /// (e.g. derived from a save-file header). Prefer [`Rng::seed`] for
    /// everyday use. Dual of [`Rng::state`].
    #[must_use]
    pub fn from_state(s: [u32; 4]) -> Self {
        debug_assert!(
            s.iter().any(|&w| w != 0),
            "xoshiro128** rejects all-zero state"
        );
        Self { s }
    }

    /// Draw the next `u32` bounded to `[0, bound)`. Uses Lemire's debiased
    /// integer-multiplication method — branch-free in the common case.
    pub fn next_bounded(&mut self, bound: u32) -> u32 {
        debug_assert!(bound > 0, "next_bounded(0) has no defined output");
        let mut x = self.next_u32();
        let mut m = u64::from(x) * u64::from(bound);
        let mut l = low_u32(m);
        if l < bound {
            let t = (u32::MAX - bound + 1) % bound;
            while l < t {
                x = self.next_u32();
                m = u64::from(x) * u64::from(bound);
                l = low_u32(m);
            }
        }
        high_u32(m)
    }
}

/// Low 32 bits of a `u64`, expressed as a masked `try_from` so clippy can prove
/// the conversion is lossless.
fn low_u32(value: u64) -> u32 {
    u32::try_from(value & u64::from(u32::MAX)).expect("masked u64 fits in u32")
}

/// High 32 bits of a `u64`. The right shift makes the result provably fit in
/// `u32` so clippy does not flag the cast.
fn high_u32(value: u64) -> u32 {
    (value >> 32) as u32
}

struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    const fn new(seed: u64) -> Self {
        Self { state: seed }
    }

    fn next_u32(&mut self) -> u32 {
        // SplitMix64 step → take the high 32 bits, which avoids easily
        // predictable low bits in the seed expansion.
        self.state = self.state.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^= z >> 31;
        (z >> 32) as u32
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::any;

    /// Reference stream generated by the canonical xoshiro128** C reference
    /// implementation (Blackman & Vigna, <https://prng.di.unimi.it>) seeded
    /// with `SplitMix64(1)` for `state[0..4]`. Pinning a published seeding
    /// scheme keeps this test stable across language implementations.
    const REFERENCE_STREAM_SEED_ONE: [u32; 8] = [
        0xb3f2_a9c5,
        0x853b_546a,
        0xdc85_6663,
        0xfaf9_6c9a,
        0xd54c_7633,
        0x3674_bd82,
        0xc813_1050,
        0x96a4_073e,
    ];

    #[test]
    fn seed_one_matches_published_reference_stream() {
        let mut rng = Rng::seed(1);
        for &expected in &REFERENCE_STREAM_SEED_ONE {
            assert_eq!(rng.next_u32(), expected);
        }
    }

    #[test]
    fn from_state_produces_same_stream_as_matching_seed_expansion() {
        let mut from_seed = Rng::seed(1);
        let expected_state = from_seed.state();
        let mut from_state = Rng::from_state(expected_state);
        for _ in 0..256 {
            assert_eq!(from_state.next_u32(), from_seed.next_u32());
        }
    }

    proptest::proptest! {
        #[test]
        fn next_bounded_returns_value_in_range(seed in any::<u64>(), bound in 1u32..=u32::MAX) {
            let mut rng = Rng::seed(seed);
            for _ in 0..16 {
                let value = rng.next_bounded(bound);
                assert!(value < bound);
            }
        }

        #[test]
        fn rng_seeded_identically_produces_identical_stream(seed in any::<u64>()) {
            let mut a = Rng::seed(seed);
            let mut b = Rng::seed(seed);
            for _ in 0..1024 {
                assert_eq!(a.next_u32(), b.next_u32());
            }
        }
    }
}
